import type { Metadata } from "next"

interface EnhancedMetaTagsProps {
  title: string
  description: string
  keywords?: string[]
  ogImage?: string
  ogType?: "website" | "article" | "profile"
  twitterCard?: "summary" | "summary_large_image"
  canonicalUrl?: string
  noIndex?: boolean
  publishedTime?: string
  modifiedTime?: string
  authorName?: string
  locale?: string
}

export function generateEnhancedMetadata({
  title,
  description,
  keywords = ["kubah masjid",
    "mimbar masjid",
    "menara masjid",
    "kerawangan",
    "awan kaligrafi",
    "ornamen islami",
    "kubah masjid murah",
    "mimbar masjid murah",
    "menara masjid murah",
    "kerawangan murah",
    "awan kaligrafi murah",
    "ornamen islami murah",
    "pembuatan masjid modern murah",
    "pembuatan masjid minimalis murah",
    "kubah masjid modern",
    "kubah GRC",
    "harga kubah masjid grc",
    "grc kubah",
    "kubah grc",
    "kubah architecture",
    "kubah grafik",
    "kubah grc motif",
    "kubah grc bekasi",
    "kubah grc adalah",
    "grc kubah menara masjid",
    "rangka kubah grc",
    "gambar kubah grc",
    "model kubah grc",
    "kubah dari grc",
    "berat kubah grc",
    "bahan kubah grc",
    "harga kubah grc diameter 4 meter",
    "mahkota kubah grc",
    "leher kubah grc",
    "pemasangan kubah grc masjid",
    "kubah grc masjid",
    "grc kubah masjid",
    "desain kubah grc",
    "pemesanan kubah GRC",
    "pemasangan kubah grc",
    "pemasangan kubah grc masjid",
    "pasang kubah grc",
    "pemasangan kubah cor",
    "cara pemasangan kubah grc",
    "menara GRC",
    "grc menara masjid",
    "rangka menara grc",
    "harga menara grc",
    "gambar menara grc",
    "menara masjid grc kubah",
    "menara masjid dari grc",
    "harga grc menara masjid",
    "menara gracia",
    "menara group",
    "menara bca green building",
    "menara great eastern",
    "menara great eastern 2",
    "menara great eastern 2 address",
    "menara great eastern kl",
    "menara great eastern address",
    "menara great eastern ampang",
    "menara great eastern jalan ampang",
    "kubah cibitung",
    "masjid GRC",
    "grc masjid krawangan",
    "grc masjid 3d warehouse",
    "mihrab masjid grc",
    "kubah masjid grc",
    "menara masjid grc",
    "ornamen masjid grc",
    "pagar masjid grc",
    "plafon masjid grc",
    "menara masjid grc kubah",
    "motif grc masjid",
    "rab menara masjid grc",
    "ornamen grc masjid",
    "kubah grc masjid",
    "grc menara masjid",
    "grc mihrab masjid",
    "grc dinding masjid",
    "roster grc masjid",
    "model grc masjid",
    "panel grc masjid",
    "grc untuk masjid",
    "kaligrafi grc masjid",
    "grc jendela masjid",
    "lisplang grc masjid",
    "grc masjid",
    "masjid grc",
    "masjid arch design",
    "masjid gresik",
    "masjid grafik",
    "masjid architecture",
    "masjid green",
    "masjid grafis",
    "masjid gren alia cikini",
    "ornamen GRC",
    "ornamen grc masjid",
    "ornamen grc terdekat",
    "ornamen grc tempel",
    "ornamen grc minimalis",
    "ornamen grc krawangan",
    "ornamen grc klasik",
    "ornamen grc dinding",
    "ornamen grc board",
    "ornamen grc pt adirahma harapan jaya",
    "ornamen grc rumah",
    "ornamen grc pagar",
    "ornamen grc relief",
    "ornamen grc pekanbaru",
    "ornamen grc adalah",
    "ornamen grc cetak",
    "ornamen grc",
    "ornamen grc dinding masjid",
    "grc ornamen",
    "ornamen grc skp",
    "ornamen tiang grc",
    "grc ornaments",
    "menara GRC",
    "menara grc",
    "grc menara masjid",
    "rangka menara grc",
    "harga menara grc",
    "gambar menara grc",
    "menara masjid grc kubah",
    "menara masjid dari grc",
    "harga grc menara masjid",
    "menara gracia",
    "menara group",
    "menara bca green building",
    "grc kubah menara masjid",
    "grc menara",
    "menara great eastern",
    "grc ornamen krawangan",
    "grc ornamen dinding",
    "grc ornamen pagar",
    "menara great eastern ampang",
    "menara great eastern jalan ampang",
    "krawangan GRC",
    "krawangan grc motif daun",
    "krawangan grc pagar",
    "krawangan grc makassar",
    "krawangan grc minimalis",
    "krawangan grc terdekat",
    "krawangan grc motif batik",
    "krawangan grc motif bunga",
    "krawangan grc mushola",
    "krawangan grc kaligrafi",
    "krawangan grc beton",
    "krawangan grc bandung",
    "krawangan grc motif",
    "grc krawangan rumah minimalis",
    "grc krawangan surabaya",
    "menara greenview",
    "menara great eastern 2",
    "menara great eastern 2 address",
    "menara great eastern kl",
    "menara great eastern address",
    "krawangan grc masjid",
    "grc krawangan pagar",
    "grc krawangan bandung",
    "grc krawangan minimalis",
    "grc krawangan semarang",
    "grc krawangan rumah",
    "grc krawangan jogja",
    "grc krawangan adalah",
    "grc krawangan cinere",
    "grc krawangan jakarta",
    "grc krawangan",
    "harga krawangan grc per m2",
    "grc krawangan batik",
    "jasa pembuatan kubah",
    "jasa pembuatan kubah masjid",
    "grc krawangan masjid",
    "grc krawangan terdekat",
    "grc krawangan bekasi",
    "grc krawangan ornamen masjid",
    "bangunan dari grc",
    "bangunan pakai grc",
    "bahan bangunan grc adalah",
    "toko bangunan grc",
    "alat bangunan grc",
    "bangunan dengan grc",
    "bangunan menggunakan grc",
    "bangunan rumah dari grc",
    "harga grc bangunan",
    "grc bahan bangunan",
    "bangunan grc",
    "grc bangunan",
    "cara pembuatan kubah masjid",
    "jasa pembuat kubah",
    "pembuatan kubah",
    "jasa pembuatan kumbung",
    "jasa pembuatan pembukuan",
    "bangunan GRC",
    "bangunan grc board",
    "grc bangunan adalah",
    "bahan bangunan grc",
    "bahan bangunan grc harga",
    "grc bahan bangunan adalah",
    "grc dalam bangunan",
    "grc untuk bangunan",
    "grc pada bangunan",
    "apa itu grc bangunan",
    "bangunan green building",
    "bangunan groin",
    "bangunan greenhouse",
    "bangunan graha maju",
    "bangunan grid",
    "bangunan gacoan",
    "bangunan green building di indonesia",
    "bangunan green arsitektur",
    "bangunan green building adalah",
    "renovasi masjid",
    "renovasi masjid nabawi",
    "renovasi masjid nabawi dilakukan pada masa khalifah",
    "renovasi masjidil haram",
    "renovasi masjid nabawi pada masa utsman bin affan",
    "renovasi masjid istiqlal",
    "renovasi masjid nabawi pada masa khalifah utsman bin affan",
    "renovasi masjid nabawi dilakukan pada masa khalifah utsman bin affan",
    "renovasi masjid agung kendal",
    "renovasi masjid nabawi terjadi pada masa khalifah",
    "renovasi masjid agung batam",
    "renovasi masjidil haram 2024",
    "renovasi masjid piss ktb",
    "renovasi masjid nabawi utsman bin affan",
    "renovasi masjid agung",
    "renovasi masjid nabawi pertama kali dilakukan di khalifah",
    "renovasi masjid agung surakarta",
    "renovasi masjid raya batam",
    "masjid renovasi",
    "proposal renovasi masjid",
    "proposal pengajuan dana renovasi masjid",
    "proposal renovasi masjid word",
    "contoh proposal renovasi masjid",
    "contoh rab renovasi masjid",
    "spanduk renovasi masjid",
    "proposal renovasi masjid pdf",
    "renovasi masjid cut meutia",
    "renovasi masjid nabawi dilakukan pada masa pemerintahan khalifah",
    "renovasi masjid nabawi terjadi pada masa",
    "renovasi masjid al falah surabaya",
    "renovasi kursi",
    "kubah revit",
    "kubah rumah",
    "renovasi kabah",
    "harga kubah GRC",
    "harga kubah grc per meter",
    "harga kubah grc diameter 4 meter",
    "harga kubah masjid bahan grc",
    "harga kubah grc per meter 2022",
    "rab renovasi masjid",
    "renovasi kubah",
    "renovasi kubah masjid",
    "proposal renovasi kubah masjid",
    "renovasi kubah islamic center",
    "renovasi kuburan",
    "renovasi ka'bah",
    "kubah grc murah",
    "grc kubah harga",
    "harga kubah masjid grc",
    "harga kubah grc diameter 2 meter",
    "harga kubah grc",
    "grc kubah",],
  ogImage = "/images/og-image.jpg",
  ogType = "website",
  twitterCard = "summary_large_image",
  canonicalUrl,
  noIndex = false,
  publishedTime,
  modifiedTime,
  authorName = "Cipta Mandiri Perkasa",
  locale = "id_ID",
}: EnhancedMetaTagsProps): Metadata {
  // Base URL for the site
  const baseUrl = "https://kubahcmp.id"

  // Ensure ogImage has absolute URL
  const ogImageUrl = ogImage.startsWith("http") ? ogImage : `${baseUrl}${ogImage}`

  // Canonical URL (default to current path if not provided)
  const canonical = canonicalUrl
    ? canonicalUrl.startsWith("http")
      ? canonicalUrl
      : `${baseUrl}${canonicalUrl}`
    : undefined

  return {
    title: title,
    description: description,
    keywords: keywords,

    // Robots meta tags
    robots: noIndex
      ? {
          index: false,
          follow: true,
          nocache: true,
          googleBot: {
            index: false,
            follow: true,
          },
        }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },

    // Open Graph meta tags
    openGraph: {
      title: title,
      description: description,
      url: canonical,
      siteName: "Cipta Mandiri Perkasa",
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      locale: locale,
      type: ogType,
      ...(publishedTime && { publishedTime }),
      ...(modifiedTime && { modifiedTime }),
      ...(authorName &&
        ogType === "article" && {
          authors: [authorName],
        }),
    },

    // Twitter meta tags
    twitter: {
      card: twitterCard,
      title: title,
      description: description,
      images: [ogImageUrl],
      creator: "@ciptamandiriperkasa",
      site: "@ciptamandiriperkasa",
    },

    // Canonical URL
    ...(canonical && { alternates: { canonical } }),

    // Additional meta tags
    authors: [{ name: authorName, url: baseUrl }],
    creator: "Cipta Mandiri Perkasa",
    publisher: "Cipta Mandiri Perkasa",

    // Verification tags
    verification: {
      google: "verification_code_here", // Replace with your Google verification code
      yandex: "verification_code_here", // Replace with your Yandex verification code
      yahoo: "verification_code_here", // Replace with your Yahoo verification code
    },

    // Other meta tags
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },
  }
}
